version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: spotify_db
    restart: always
    environment:
      POSTGRES_USER: spotify_user
      POSTGRES_PASSWORD: spotify_pass_2024
      POSTGRES_DB: spotify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: